name: Build and Push Docker Image

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Bump version and add commit ID
      run: |
        version=$(cat version.txt)
        commit_id=$(git rev-parse --short HEAD)
        version="${version}-${commit_id}"
        echo "VERSION=$version" >> $GITHUB_ENV

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./DockerfileMinimalWebAPI
        push: true
        tags: |
          yadavpk/minimalwebapi:${{ env.VERSION }}
          yadavpk/minimalwebapi:latest
